INSERT INTO institution (ins_id, abbreviation, name, street_name, street_number, zip, city) VALUES (78001, "NTUA", "National Technical University of Athens", "Patision", 682, 10682, "Athens");
INSERT INTO institution (ins_id, abbreviation, name, street_name, street_number, zip, city) VALUES (78002, "NKUA", "National and Kapodistrian University of Athens", "Imitou", 784, 15784, "Athens");
INSERT INTO institution (ins_id, abbreviation, name, street_name, street_number, zip, city) VALUES (78003, "UOP", "University of Patras", "Ippokratous", 504, 26504, "Patras");
INSERT INTO institution (ins_id, abbreviation, name, street_name, street_number, zip, city) VALUES (78004, "UTH", "University of Thessaly", "Argonafton", 221, 38221, "Volos");
INSERT INTO institution (ins_id, abbreviation, name, street_name, street_number, zip, city) VALUES (78005, "UNIWA", "University of West Attica", "Spiridonos", 243, 12243, "Athens");
INSERT INTO institution (ins_id, abbreviation, name, street_name, street_number, zip, city) VALUES (78006, "TUC", "Technical University of Crete", "Akrotiri", 100, 73100, "Chania");
INSERT INTO institution (ins_id, abbreviation, name, street_name, street_number, zip, city) VALUES (78007, "DUTH", "Democritus University of Thrace", "Campus", 100, 69100, "Komotini");
INSERT INTO institution (ins_id, abbreviation, name, street_name, street_number, zip, city) VALUES (78008, "AUTH", "Aristotle University of Thessaloniki", "Miller", 124, 54124, "Thessaloniki");
INSERT INTO institution (ins_id, abbreviation, name, street_name, street_number, zip, city) VALUES (78009, "AUEB", "Athens University of Economics and Business", "Patision", 34, 10434, "Athens");
INSERT INTO institution (ins_id, abbreviation, name, street_name, street_number, zip, city) VALUES (78010, "UNIPI", "University of Piraeus", "Karaoli", 534, 18534, "Piraeus");
INSERT INTO institution (ins_id, abbreviation, name, street_name, street_number, zip, city) VALUES (78011, "NOA", "National Oservatory of Athens", "Nimfon", 10, 11810, "Athens");
INSERT INTO institution (ins_id, abbreviation, name, street_name, street_number, zip, city) VALUES (78012, "NCSR", "National Center for Scientific Research Demokritos", "Neapoleos", 341, 15341, "Athens");
INSERT INTO institution (ins_id, abbreviation, name, street_name, street_number, zip, city) VALUES (78013, "GRNET", "S.A. National Infrastructures for Research and Technology", "Kifisias", 3, 11523, "Athens");
INSERT INTO institution (ins_id, abbreviation, name, street_name, street_number, zip, city) VALUES (78014, "NHRF", "National Hellenic Research Foundation", "Konstantinou", 635, 11635, "Athens");
INSERT INTO institution (ins_id, abbreviation, name, street_name, street_number, zip, city) VALUES (78015, "CERTH", "Centre for Research & Technology Hellas", "Egialias", 25, 15125, "Athens");
INSERT INTO institution (ins_id, abbreviation, name, street_name, street_number, zip, city) VALUES (78016, "GAEC", "Greek Atomic Energy Commissions", "Neapoleos", 41, 15341, "Athens");
INSERT INTO institution (ins_id, abbreviation, name, street_name, street_number, zip, city) VALUES (78017, "HCMR", "Hellenic Centre for Marine Research", "Vouliagmenis", 452, 16452, "Athens");
INSERT INTO institution (ins_id, abbreviation, name, street_name, street_number, zip, city) VALUES (78018, "FORTH", "Foundation for Research and Technology - Hellas", "Plastira", 13, 70013, "Heraklion");
INSERT INTO institution (ins_id, abbreviation, name, street_name, street_number, zip, city) VALUES (78019, "CRES", "Centre for Renewable Energy Sources and Saving", "Marathonos", 9, 19009, "Athens");
INSERT INTO institution (ins_id, abbreviation, name, street_name, street_number, zip, city) VALUES (78020, "BSRC", "Fleming Biomedical Sciences Research Center Alexander Fleming", "Fleming", 672, 16672, "Athens");
INSERT INTO institution (ins_id, abbreviation, name, street_name, street_number, zip, city) VALUES (78021, "RF", "Research Focus", "Emeral", 102, 8102, "Athens");
INSERT INTO institution (ins_id, abbreviation, name, street_name, street_number, zip, city) VALUES (78022, "SP", "Scipark", "Cambridge", 502, 86502, "Patras");
INSERT INTO institution (ins_id, abbreviation, name, street_name, street_number, zip, city) VALUES (78023, "SC", "Scolax", "Scheuvront", 66, 94566, "Piraeus");
INSERT INTO institution (ins_id, abbreviation, name, street_name, street_number, zip, city) VALUES (78024, "ELY", "Experiment.ly", "Hinkle", 38, 2038, "Thessaloniki");
INSERT INTO institution (ins_id, abbreviation, name, street_name, street_number, zip, city) VALUES (78025, "IC", "Intercomp", "Essex", 93, 27893, "Chania");
INSERT INTO institution (ins_id, abbreviation, name, street_name, street_number, zip, city) VALUES (78026, "LL", "Linkage Labs", "Hog", 466, 60466, "Athens");
INSERT INTO institution (ins_id, abbreviation, name, street_name, street_number, zip, city) VALUES (78027, "LM", "LabMouse", "Hedge", 701, 7701, "Athens");
INSERT INTO institution (ins_id, abbreviation, name, street_name, street_number, zip, city) VALUES (78028, "OCL", "Occulab", "Freshour", 205, 78205, "Tripoli");
INSERT INTO institution (ins_id, abbreviation, name, street_name, street_number, zip, city) VALUES (78029, "CL", "Config Lab", "Nicholas", 427, 66427, "Lamia");
INSERT INTO institution (ins_id, abbreviation, name, street_name, street_number, zip, city) VALUES (78030, "FL", "Faculty Labs", "Johnstown", 148, 60148, "Sparta");
