INSERT INTO program (prog_id, name, department) VALUES (23001, "Thales", "Program Management and Monitoring");
INSERT INTO program (prog_id, name, department) VALUES (23002, "Anaximander", "Enviromental Research and Sustainable Development");
INSERT INTO program (prog_id, name, department) VALUES (23003, "Pythagoras", "Design and Scheduling");
INSERT INTO program (prog_id, name, department) VALUES (23004, "Anaxagoras", "Innovative Actions Planning");
INSERT INTO program (prog_id, name, department) VALUES (23005, "Hippocrates", "Program Management and Monitoring");
INSERT INTO program (prog_id, name, department) VALUES (23006, "Eudoxus", "Design and Scheduling");
INSERT INTO program (prog_id, name, department) VALUES (23007, "Aristotle", "Agriculture and Food Processing");
INSERT INTO program (prog_id, name, department) VALUES (23008, "Theophrastus", "Enviromental Research and Sustainable Development");
INSERT INTO program (prog_id, name, department) VALUES (23009, "Aristarchus", "Design and Scheduling");
INSERT INTO program (prog_id, name, department) VALUES (23010, "Euclid", "Innovative Actions Planning");
INSERT INTO program (prog_id, name, department) VALUES (23011, "Archimedes", "Program Management and Monitoring");
INSERT INTO program (prog_id, name, department) VALUES (23012, "Eratosthenes", "Agriculture and Food Processing");
INSERT INTO program (prog_id, name, department) VALUES (23013, "Hipparchus", "Agriculture and Food Processing");
INSERT INTO program (prog_id, name, department) VALUES (23014, "Ptolemy", "Design and Scheduling");
INSERT INTO program (prog_id, name, department) VALUES (23015, "Diophantus", "Enviromental Research and Sustainable Development");
INSERT INTO program (prog_id, name, department) VALUES (23016, "Hero", "Design and Scheduling");
INSERT INTO program (prog_id, name, department) VALUES (23017, "Xenocrates", "Enviromental Research and Sustainable Development");
INSERT INTO program (prog_id, name, department) VALUES (23018, "Xenagoras", "Design and Scheduling");
INSERT INTO program (prog_id, name, department) VALUES (23019, "Cleomedes", "Innovative Actions Planning");
INSERT INTO program (prog_id, name, department) VALUES (23020, "Pytheas", "Enviromental Research and Sustainable Development");
INSERT INTO program (prog_id, name, department) VALUES (23021, "Theodosius", "Innovative Actions Planning");
INSERT INTO program (prog_id, name, department) VALUES (23022, "Epicurus", "Design and Scheduling");
INSERT INTO program (prog_id, name, department) VALUES (23023, "Heraclitus", "Design and Scheduling");
INSERT INTO program (prog_id, name, department) VALUES (23024, "Plato", "Innovative Actions Planning");
INSERT INTO program (prog_id, name, department) VALUES (23025, "Eupalinos", "Program Management and Monitoring");
INSERT INTO program (prog_id, name, department) VALUES (23026, "Leophanes", "Agriculture and Food Processing");
INSERT INTO program (prog_id, name, department) VALUES (23027, "Pythias", "Innovative Actions Planning");
INSERT INTO program (prog_id, name, department) VALUES (23028, "Callistatus", "Agriculture and Food Processing");
INSERT INTO program (prog_id, name, department) VALUES (23029, "Dionysiades", "Design and Scheduling");
INSERT INTO program (prog_id, name, department) VALUES (23030, "Xenarchus", "Design and Scheduling");
